# Generated by Django 2.2.6 on 2020-02-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0002_friend_lendedbooks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lendedbooks',
            name='date_lend_out',
            field=models.DateField(blank=True, null=True),
        ),
    ]
