# Generated by Django 2.2.6 on 2020-04-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0005_auto_20200412_1448'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lendedbooks',
            options={'verbose_name': 'Одолженная книга', 'verbose_name_plural': 'Одолженные книги'},
        ),
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, upload_to='covers'),
        ),
    ]
